services:
  client:
    build: ./client
    ports:
      - "3003:80"
    depends_on:
      - server

  server:
    build: ./server
    volumes:
      - /root/uploads:/app/uploads
    expose:
      - "3002"
